# MAFFT Testing
# It turns out, that if you use brew, then you can install MAFFT
# brew install mafft
import os
from Bio import SeqIO
import matplotlib.pyplot as plt

fastafiles = list(SeqIO.parse('seqs_trial.fasta', format = 'fasta'))

# Confirm the file loaded properly
for entry in fastafiles:
    print(entry.id)
    
# Make a dictionary for easy access moving forward.
sequences = {}
for entry in fastafiles:
    sequences[entry.id] = entry
    
# Use mafft for simple alignment - we first must make sure mafft is installed
# use this: conda install -c biocore mafft
# update 1.24.2024: conda install bioconda::mafft

os.system('mafft seqs_trial.fasta > seqs_ali.fasta') # assign aligned sequences to seqs_ali

ali_files = list(SeqIO.parse('seqs_ali.fasta', format = 'fasta'))

# Confirm the file loaded properly
for entry in ali_files:
    print(entry.id)
    print(len(entry.seq))

# Make a dictionary for easy access moving forward.
sequences_ali = {}
for entry in ali_files:
    sequences_ali[entry.id] = entry

# For now, we are just going to look at the spike protein. 21563...25384
# But we need to re-align this range with the new alignments generated by mafft

def gapped_pos(sequ, pos):
    non_gap = 0
    gaps = 0
    for nt in sequ:
        if nt != '-':
            non_gap += 1
        else:
            gaps += 1
        if non_gap == pos:
            return pos + gaps

spike_start = gapped_pos(sequences['Wuhan_strain'].seq, 21563)
spike_end = gapped_pos(sequences['Wuhan_strain'].seq, 25384)

# Now let's make a dictionary of the spike protein sequences to work with
spikes = {}
for s in ali_files:
    spikes[s.id] = s.seq[21563-1:25393]
    
# Find the mutations in the spike protein!    
def get_mutations(initial, variant):
    seq_list = list(zip(initial, variant))
    mut_out = []
    for pos, nt in enumerate(seq_list):
        if nt[0] != nt[1]:
            # print(nt[0].upper() + str(pos + 1) + nt[1].upper())
            mut_out.append(nt[0].upper() + str(pos + 1) + nt[1].upper())
    return mut_out
            
            
# ref_sequence = input('What is the name of the reference sequence?: ')
# var_sequence = input('What is the name of the variant sequence?: ')


# Yet, these may be synonymous. Let's look for non-synonymous changes!
# When we aligned originally, our program was unaware. The gaps may cause errors.
# Take spike nt sequences generated, remove dashes, add to a file, translate them
# with biopython's .translate() feature, then re-align them once more.

with open('spikes.fasta', 'w') as f:
    for spike in spikes:
        out = spikes[spike].replace('-', '').translate() # change to AAs!
        f.write('>' + spike + '\n')
        f.write(str(out).upper()+'\n')

# now, align the spikes!
os.system('mafft --genafpair spikes.fasta > spikes_ali.fasta')

spikes_aa = list(SeqIO.parse('spikes_ali.fasta', format = 'fasta'))

# and create a dictionary with the amino acid sequence we have generated
spike_aa = {}
for entry in spikes_aa:
    spike_aa[entry.id] = entry
    

mutations = {}
for item in spike_aa:
    mutations[item] = get_mutations(spike_aa['Wuhan_strain'].seq, spike_aa[item])

plt.figure(figsize = (15, 5))
for y, item in enumerate(sequences):
    plt.plot((0, len(sequences['Wuhan_strain'])), (y,y), color = 'lightgrey')
    plt.text(-160, y +.35, item, va = 'center', ha = 'left')
    
    for mutation in mutations[item]:
        pos = int(mutation[1:-1])
        aa_change = mutation[-1]
        plt.text(pos, y, aa_change, va = 'center', ha = 'center')
    
    plt.xlim(-175, len(spike_aa['Wuhan_strain']) + 100)
    plt.ylim(-.75, len(sequences) - 0.25)
plt.show()